// ============================================================
// Enums do Modulo Contabil
// ============================================================

export enum TipoConta {
  ATIVO = 'ATIVO',
  PASSIVO = 'PASSIVO',
  RECEITA = 'RECEITA',
  DESPESA = 'DESPESA',
  PATRIMONIO_LIQUIDO = 'PATRIMONIO_LIQUIDO',
}

export enum NaturezaConta {
  DEVEDORA = 'DEVEDORA',   // Ativo e Despesa
  CREDORA = 'CREDORA',     // Passivo, PL e Receita
}

export enum ClasseConta {
  SINTETICA = 'SINTETICA',  // Grupo (nao recebe lancamento)
  ANALITICA = 'ANALITICA',  // Conta final (recebe lancamento)
}

export enum StatusLancamento {
  RASCUNHO = 'RASCUNHO',
  CONFIRMADO = 'CONFIRMADO',
  ESTORNADO = 'ESTORNADO',
}

export enum OrigemLancamento {
  MANUAL = 'MANUAL',
  AUTOMATICO = 'AUTOMATICO',
  IMPORTACAO = 'IMPORTACAO',
  ESTORNO = 'ESTORNO',
}

export enum TipoOperacaoContabil {
  // === VENDAS ===
  VENDA_DINHEIRO = 'VENDA_DINHEIRO',
  VENDA_PIX = 'VENDA_PIX',
  VENDA_CARTAO_CREDITO = 'VENDA_CARTAO_CREDITO',
  VENDA_CARTAO_DEBITO = 'VENDA_CARTAO_DEBITO',
  VENDA_BOLETO = 'VENDA_BOLETO',
  VENDA_CREDIARIO = 'VENDA_CREDIARIO',
  VENDA_VALE = 'VENDA_VALE',

  // === COMPENSACAO CARTAO ===
  COMPENSACAO_CARTAO = 'COMPENSACAO_CARTAO',
  TAXA_OPERADORA_CARTAO = 'TAXA_OPERADORA_CARTAO',

  // === BOLETOS ===
  RECEBIMENTO_BOLETO = 'RECEBIMENTO_BOLETO',
  TARIFA_BOLETO = 'TARIFA_BOLETO',

  // === ANTECIPACAO ===
  ANTECIPACAO_CARTAO = 'ANTECIPACAO_CARTAO',
  CUSTO_ANTECIPACAO_CARTAO = 'CUSTO_ANTECIPACAO_CARTAO',
  ANTECIPACAO_BOLETO = 'ANTECIPACAO_BOLETO',
  CUSTO_ANTECIPACAO_BOLETO = 'CUSTO_ANTECIPACAO_BOLETO',

  // === DESCONTO BOLETO ===
  DESCONTO_BOLETO = 'DESCONTO_BOLETO',
  CUSTO_DESCONTO_BOLETO = 'CUSTO_DESCONTO_BOLETO',

  // === BOLETO DEVOLVIDO ===
  BOLETO_DEVOLVIDO = 'BOLETO_DEVOLVIDO',
  RECUPERACAO_BOLETO_DEVOLVIDO = 'RECUPERACAO_BOLETO_DEVOLVIDO',
  PREJUIZO_BOLETO_DEVOLVIDO = 'PREJUIZO_BOLETO_DEVOLVIDO',

  // === EMPRESTIMO ===
  EMPRESTIMO_LIBERACAO = 'EMPRESTIMO_LIBERACAO',
  EMPRESTIMO_PAGAMENTO_PARCELA = 'EMPRESTIMO_PAGAMENTO_PARCELA',
  EMPRESTIMO_JUROS = 'EMPRESTIMO_JUROS',
  IOF_EMPRESTIMO = 'IOF_EMPRESTIMO',

  // === VALES / CREDITOS ===
  EMISSAO_VALE = 'EMISSAO_VALE',
  UTILIZACAO_VALE = 'UTILIZACAO_VALE',

  // === COMPRAS ===
  COMPRA_MERCADORIA = 'COMPRA_MERCADORIA',
  PAGAMENTO_FORNECEDOR = 'PAGAMENTO_FORNECEDOR',

  // === FOLHA ===
  FOLHA_PAGAMENTO = 'FOLHA_PAGAMENTO',
  PAGAMENTO_SALARIOS = 'PAGAMENTO_SALARIOS',

  // === TAXAS BANCARIAS ===
  TAXA_BANCARIA_MANUTENCAO = 'TAXA_BANCARIA_MANUTENCAO',
  CHEQUE_ESPECIAL_JUROS = 'CHEQUE_ESPECIAL_JUROS',
}

export enum TipoContaBancaria {
  CONTA_CORRENTE = 'CONTA_CORRENTE',
  CONTA_POUPANCA = 'CONTA_POUPANCA',
  CONTA_PAGAMENTO = 'CONTA_PAGAMENTO',
  CONTA_DIGITAL = 'CONTA_DIGITAL',
}
